name: environment
channels:
  - conda-forge
dependencies:
  - numpy
  - jupyter
  - pandas
  - requests
  - openpyxl
  - scipy
  - rpy2
  - matplotlib
  - statsmodels
  - pip:
    - yfinance
    - datetime
