name: stockproject
channels:
  - conda-forge
dependencies:
  - python
  - jupyter
  - notebook
  - numpy
  - pandas
  - requests
  - matplotlib
  - scipy
  - statsmodels
  - pip
  - pip:
    - datetime
    - yfinance
    - rpy2
    - calendar
    - io
